theme: jekyll-theme-cayman
plugins:
  - jekyll-archives
  - jekyll-relative-links
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
relative_links:
  enabled: true
  collections: true